class LexerType:
    RANGE_IDENTIFIER = "RANGE_IDENTIFIER"
    RANGE = "RANGE"
    OPEN_CURLY_BRACKETS = "{"
    CLOSE_CURLY_BRACKETS = "}"
    SEMI_COLON = ";"
    COLON = ":"
    EQUAL = "="
    INVALID = "INVALID"
    CSS_VARIABLE = "CSS_VARIABLE"
    ELEMENT_CLASS ="ELEMENT_CLASS"
    ELEMENT_ID = "ELEMENT_ID"
    